In [22]:
import numpy as np

In [23]:
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [24]:
print(type(arr))

<class 'numpy.ndarray'>


In [25]:
arr = np.array(42)

print(arr)

42


In [26]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [30]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])


print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [28]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [29]:
arr2 = np.array([1,2,3,4], ndmin=5)
print(arr2)
print('number of dimensions: ', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions:  3
